<?php

namespace Neoan3\Component\Image;

use Neoan3\Core\Event;
use Neoan3\Frame\VastN3;

/**
 * Class ImageController
 * @package Neoan3\Component\Image
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */

class ImageController extends VastN3{

    /**
    * GET: api.v1/image
    * GET: api.v1/image/{id}
    * GET: api.v1/image?{query-string}
    * @param string|null $id
    * @param array $params
    * @return array
    */
    function getImage(?string $id = null, array $params = []): array
    {
        // Restrict access to logged in users?
        $this->provider['auth']->restrict();
        // (or without dependency on Demo-Frame: $this->provider['auth']->restrict())
        if($id){
            // Retrieve a model?
            return $this->loadModel(\Neoan3\Model\Image\ImageModel::class)::get($id);
        }

        return $params;
    }

    /**
     * POST: api.v1/image
     * @param $body
     * @return array
     */
    function postImage(array $body): array
    {
        return $body;
    }
}
