<?php

namespace Neoan3\Component\It;

use Neoan3\Frame\VastN3;

/**
 * Class TestController
 * @package Neoan3\Component\It
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */

class ItController extends VastN3 {
    /**
     * Route: Test
     */
    function init(): void
    {
        $this->renderer->includeElement('It');
        $this->hook('main', 'it', []);
        $this->output();
    }

}
