<?php

namespace Neoan3\Component\Cart;

use Neoan3\Frame\VastN3;

/**
 * Class TestController
 * @package Neoan3\Component\Cart
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */

class CartController extends VastN3 {
    /**
     * Route: Test
     */
    function init(): void
    {
        $this->renderer->includeElement('Cart');
        $this->hook('main', 'cart');
        $this->output();
    }

}
