<?php

namespace Neoan3\Component\Ui;

use Neoan3\Apps\Template;
use Neoan3\Frame\VastN3;

/**
 * Class TestController
 * @package Neoan3\Component\Test
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */

class UiController extends VastN3 {
    /**
     * Route: Test
     */
    function init(): void
    {
        $this->setTitle('UI components');
//        $this->hook('main', 'ui');
        $this->renderer->includeElement('Ui');
        $this->hook('main', 'ui');
        $this->output();
    }
    function getUi($which, $query=[])
    {

        header('Content-Type: text/javascript');
        $this->renderer->includeElement('ui.modal', [], path . '/component/Ui/lib/ui.'.$which.'.vue');
        $params = [
            'template' => substr($this->renderer->hooks['templates'],strlen('<template>'), strlen('</template>') * -1)
        ];
        $component = Template::embrace($this->renderer->hooks['components'],$params);
        echo $component;
        exit();
    }

}
