<?php

namespace Neoan3\Component\Test;

use Neoan3\Frame\VastN3;

/**
 * Class TestController
 * @package Neoan3\Component\Test
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */

class TestController extends VastN3 {
    /**
     * Route: Test
     */
    function init(): void
    {
        $this->hook('main', 'test');
        $this->renderer->includeElement('Test');
        $this->output();
    }

}