<?php

namespace Neoan3\Component\Products;

use Neoan3\Apps\Cache;
use Neoan3\Frame\VastN3;
use Neoan3\Frame\VueRenderer;

/**
 * Class TestController
 * @package Neoan3\Component\Products
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */

class ProductsController extends VastN3 {

    /**
     * Route: Test
     */
    function init(): void
    {
        $products = $this->getProducts();
        $this->renderer->storeObject('products', $products);
        $this->renderer->includeElement('Products', ['products' => $products]);
        $this->hook('main', 'products', ['products' => $products]);
        $this->output();
    }
    function getProducts($search = [])
    {
        $cachePath = __DIR__ . '/products.json';
        if(!file_exists($cachePath)){
            $products = json_decode(file_get_contents('https://staging.everdrop.com/api/products/ch'),true);
            foreach ($products as $i=>$product){
                unset($products[$i]['body_html']);
            }
            file_put_contents($cachePath, json_encode($products));
        }

        return json_decode(file_get_contents($cachePath),true);

    }

}
