<?php

namespace Neoan3\Component\Products;

use Neoan3\Apps\Cache;
use Neoan3\Frame\VastN3;
use Neoan3\Frame\VueRenderer;

/**
 * Class TestController
 * @package Neoan3\Component\Products
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */

class ProductsController extends VastN3 {

    /**
     * Route: Test
     */
    function init(): void
    {
        $products = $this->getProducts();
        $this->renderer->storeObject('products', $products);
        $this->hook('main', 'products', ['products' => $products]);
        $this->output();
    }
    function getProducts($search = [])
    {
        $cachePath = __DIR__ . '/products.json';
        return json_decode(file_get_contents($cachePath),true);

    }

}
